client_id: Paymentapp-MPqoye7a26
client_secret: ff18fa56-5a7f-4081-bdc7-acd6d62e642b
url: https://sandbox-api.veem.com/
authorizationCode: VeemAbckeieifh
redirectUrl: http://your-veem-redirct.yourbusiness.com